### ISSUE TITLE
Consider adding a license

### ISSUE THREAD

**Issue by tesfaldet** [jonlil/mongoose-paginate#7]
I'd like to use some code from this library in a library that I'm developing that I'd like to publish and open source (MIT) on Github. I would include a copy of your license in my library; would you consider open sourcing this under the MIT License?

**Comment by jonlil** [comment]
Hello, good point. I'm adding MIT license. Just out of curiosity, what code are you going to reuse? :)

**Comment by jonlil** [comment]
fixed in e3af2a16fe9a04b7bb844d06424417b0bf4e3067

**Comment by tesfaldet** [comment]
Awesome! Thanks :smile: 

I'm looking to use the execPagination function https://github.com/jonlil/mongoose-paginate/blob/master/lib/index.js#L14 and modify it for a different style of optimized pagination. I'll let you know when I publish it! Shouldn't take too long.

**Comment by tesfaldet** [comment]
It took a while but here's what I've got so far! https://www.npmjs.com/package/mongoose-opt-paginate
